### ISSUE TITLE
preprocessed 执行失败

### ISSUE THREAD

**Issue by hhhynnn** [zh-plus/openlrc#20]
ln_path = ln_path.rename(ln_path.parent / f'{audio_name}_preprocessed.wav')
这一步执行失败，没反应，导致后面报错：
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

**Comment by zh-plus** [comment]
Check the solution here: https://github.com/zh-plus/openlrc/discussions/15#discussioncomment-7249044

**Comment by hhhynnn** [comment]
不，上面这个把代码放进 main 块的没用，通过另一个途径解决了：
按照 whisper 官方 README 配置好 whisper：
https://github.com/openai/whisper

**Comment by VertofChest** [comment]
This answer did not help
