### ISSUE TITLE
Suggest to use cloudflare workers ai api to lower the usage threshold

### ISSUE THREAD

**Issue by zhu327** [zh-plus/openlrc#25]
Suggest to use cloudflare workers ai api to lower the usage threshold

https://developers.cloudflare.com/workers-ai/models/speech-recognition/

**Comment by zh-plus** [comment]
I am not very familiar with cloudflare-worker-AI, but this project uses functions provided by faster-whisper, such as VAD. Many model settings (such as [asr_options, vad_options](https://github.com/zh-plus/openlrc/blob/8813d8229a6f292dbe67e42b8e31a427ef5d1c3d/openlrc/defaults.py#L6C14-L6C14)) are also related to faster-whisper.

In addition, openlrc will provide options for using denoising models for audio preprocessing, which also require the use of GPU. Therefore, I am temporarily not considering scenarios where it runs on low-load (pure CPU) machines.

If you have a viable solution to address the aforementioned issues, we can continue the discussion or you may submit a PR.
