### ISSUE TITLE
小建议-清除中间文件

### ISSUE THREAD

**Issue by dreammis** [zh-plus/openlrc#30]
项目很棒，我用来翻译视频，英文的视频，用base已经很好了

就是有个问题，每次生成就会伴随着一大堆的临时文件，根目录的wav，还有preprocessed文件夹，里面也是大量文件

希望空余了，可以设置个参数，可以在任务结束后，清除这些东西

我尝试修改代码，但是有些部分，不敢动。因为可能哪里就会用到这个文件😝

**Comment by zh-plus** [comment]
OK 下一个版本会增加一个类似的选项

**Comment by dreammis** [comment]
> OK 下一个版本会增加一个类似的选项

感謝👍
