### ISSUE TITLE
安装错误   ERROR: Failed building wheel for thinc

### ISSUE THREAD

**Issue by maotouying111** [zh-plus/openlrc#39]
note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for thinc
      Failed to build thinc
      ERROR: Could not build wheels for thinc, which is required to install pyproject.toml-based projects
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

pip setuptools wheel都是最新版本，spacy没有问题，thinc也符合spacy条件 PyTorch也是最新版本

系统是win11 cuda版本是cuda12.4

**Comment by zh-plus** [comment]
Have you ever tried solutions in https://stackoverflow.com/questions/43370851/failed-building-wheel-for-spacy?
