### ISSUE TITLE
 Does openlrc support using google gemini for subtitle translation?

### ISSUE THREAD

**Issue by MaleicAcid** [zh-plus/openlrc#43]
Gemini/Gemini pro is free and similar powerful as GPT4.
Does openlrc support using google gemini for subtitle translation now?

**Comment by zh-plus** [comment]
No, but I will consider adding support for Gemini in the next major version.

**Comment by MaleicAcid** [comment]
Thanks for your efforts on openlrc. This will help me to a greate extent.

**Comment by zh-plus** [comment]
Supported in version 1.5.0

```python
lrcer = LRCer(chatbot_model='gemini-1.5-flash')
```
