### ISSUE TITLE
Support deepseek api in translate task

### ISSUE THREAD

**Issue by MaleicAcid** [zh-plus/openlrc#52]
DeepSeek claims to provide a cheap(especially when the input hits the cache)  large model API service which is friendly to mainland China and not inferior to gpt-3.5 in AlignBench and MT-Bench.

> DeepSeek has implemented Context Caching on Disk technology. ...For cache hits, DeepSeek charges $0.014 per million tokens, slashing API costs by up to 90%.  ref@https://platform.deepseek.com/api-docs/zh-cn/news/news0802

DeepSeek claims to use an API format compatible with OpenAI. see ref@[deepseek-api doc](https://platform.deepseek.com/api-docs/zh-cn/)

**Comment by zh-plus** [comment]
We can now use the DeepSeek model, as it offers an OpenAI-compatible API.

```python
lrcer = LRCer(chatbot_model='openai: deepseek-chat', base_url_config={'openai': 'https://api.deepseek.com'})
```

Remember to change your `OPENAI_API_KEY` value to the provided deepseek API key.
