### ISSUE TITLE
Support Ollama please

### ISSUE THREAD

**Issue by MaleicAcid** [zh-plus/openlrc#56]
[Ollama](https://github.com/ollama/ollama) allow user to deploy open source llm service both in physical machine and serverless gpu server(through docker).

Ollama now has built-in compatibility with the OpenAI [Chat Completions API](https://github.com/ollama/ollama/blob/main/docs/openai.md),
Please consider supporting the use of  ollama  in translation task.

**Comment by zh-plus** [comment]
If Ollama already supports an OpenAI-compatible API, users can first run an LLM service (for example, running llama3 at 127.0.0.1:1234/v1) and then use the following code to set up Ollama as the backend:
```python
lrcer = LRCer(chatbot_model='openai: llama3',
              base_url_config={'openai': 'http://127.0.0.1:1234/v1/'})
```
